[package]
name = "env-inventory"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
resolver = "2"
authors = [ "Ahmed Masud <ahmed.masud@saf.ai>"]
edition = "2021"
rust-version = "1.61"

[lib]

[dependencies]
inventory = "0.3"
thiserror = "1.0"
toml = "0.8.0"
tracing = "*"

[profile.release]
incremental = false

[profile.dev]
incremental = false

[dev-dependencies]
tempfile = "3.8.0"
